[tool.poetry]
name = "neocore"
version = "0.1.0"
description = "A package for developing AI assistants."
authors = ["Evgeniy Kononov"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
